package com.boot.entity;
// Generated 2015-12-30 23:44:54 by Hibernate Tools 4.3.1



/**
 * EmpDetails generated by hbm2java
 */
public class EmpDetails  implements java.io.Serializable {


     private String name;
     private Employee employee;
     private String birthday;
     private String qualification;
     private String school;
     private String skill;
     private String address;
     private String mobile;
     private String qq;
     private String email;
     private String desiredCity;
     private int salary;

    public EmpDetails() {
    }

	
    public EmpDetails(String name, Employee employee, String birthday, String skill, String address, String desiredCity, int salary) {
        this.name = name;
        this.employee = employee;
        this.birthday = birthday;
        this.skill = skill;
        this.address = address;
        this.desiredCity = desiredCity;
        this.salary = salary;
    }
    public EmpDetails(String name, Employee employee, String birthday, String qualification, String school, String skill, String address, String mobile, String qq, String email, String desiredCity, int salary) {
       this.name = name;
       this.employee = employee;
       this.birthday = birthday;
       this.qualification = qualification;
       this.school = school;
       this.skill = skill;
       this.address = address;
       this.mobile = mobile;
       this.qq = qq;
       this.email = email;
       this.desiredCity = desiredCity;
       this.salary = salary;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public String getSkill() {
        return this.skill;
    }
    
    public void setSkill(String skill) {
        this.skill = skill;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDesiredCity() {
        return this.desiredCity;
    }
    
    public void setDesiredCity(String desiredCity) {
        this.desiredCity = desiredCity;
    }
    public int getSalary() {
        return this.salary;
    }
    
    public void setSalary(int salary) {
        this.salary = salary;
    }




}


