package com.boot.entity;
// Generated 2015-12-30 23:44:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int id;
     private String password;
     private Set empDetailses = new HashSet(0);

    public Employee() {
    }

	
    public Employee(int id, String password) {
        this.id = id;
        this.password = password;
    }
    public Employee(int id, String password, Set empDetailses) {
       this.id = id;
       this.password = password;
       this.empDetailses = empDetailses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getEmpDetailses() {
        return this.empDetailses;
    }
    
    public void setEmpDetailses(Set empDetailses) {
        this.empDetailses = empDetailses;
    }




}


